### ISSUE TITLE
Coding of categorical and continuous variables in tgvars seems reversed in help file, compared to code

### ISSUE THREAD

**Issue by marjoleinF** [madanstat/LongCART#1]
In package **`LongCART`** (version 2.0), the help file of function `LongCART` reads: 

`tgvars` [...] For each of continuous partitioning variables, specify 0 and for each of the categorical partitioning variables, specify 1. [...]

In the code of function `LongCART` it reads: 

        if (tgvars[v] == 0) 
          stab.pval[v] <- StabCat(data = data1, patid = "patid", 
                                  fixed = fixed, splitvar = splitvar)$pval
        if (tgvars[v] == 1) 
          stab.pval[v] <- StabCont(data = data1, patid = "patid", 
                                   fixed = fixed, splitvar = splitvar)$pval

**Comment by madanstat** [comment]
Hi Marjolein,

Thank you very much for pointing out the inconsistency in the help file. I will take care of that in the next version. Thanks.


Best regards,
Madan G Kundu, Ph.D.
Manager, Statitstics

AbbVie Inc.

Email: madan_g.kundu@yahoo.com     On Tuesday, May 19, 2020, 05:00:59 AM CDT, Marjolein Fokkema <notifications@github.com> wrote:  
 
 


In package LongCART (version 2.0), the help file of function LongCART reads:

tgvars [...] For each of continuous partitioning variables, specify 0 and for each of the categorical partitioning variables, specify 1. [...]

In the code of function LongCART it reads:
    if (tgvars[v] == 0)       stab.pval[v] <- StabCat(data = data1, patid = "patid",                               fixed = fixed, splitvar = splitvar)$pval    if (tgvars[v] == 1)       stab.pval[v] <- StabCont(data = data1, patid = "patid",                                fixed = fixed, splitvar = splitvar)$pval

**Comment by marjoleinF** [comment]
Wonderful! Thanks for the neat package!
