### ISSUE TITLE
R to PYTHON?

### ISSUE THREAD

**Issue by simonprovost** [madanstat/LongCART#3]
Dear Author,

Any plan transposing your current LongCART approach in Python?

Best wishes,

**Comment by madanstat** [comment]
Hi... I am not familiar with programming in Python. But that is a good suggestion indeed. Thanks!

**Comment by simonprovost** [comment]
Would you be open to a shared contribution? I will look at the code afterward but I am afraid first not to know where to start and second if it is huge.

Cheers.

**Comment by madanstat** [comment]
Sure - I am very much open to the idea of shared contribution. You can send me an email at madan_g.kundu@yahoo.com .

**Comment by simonprovost** [comment]
Simply checking prior anything. Would this current LongCart version handle classification? In my current hospital's uskecase we are looking for classification rather than regression.

**Comment by madanstat** [comment]
No - it does not handle classification. It's only about regression. Thanks!

**Comment by simonprovost** [comment]
Okay got it. I guess as soon as I am needing regression type of task I will get back to you with an idea on how to transpose your code in python, at the moment I am focussed on classification.

**Comment by madanstat** [comment]
Great... I would look forward to hearing from you.
